travis:
  secure:
    BINSTAR_TOKEN: jcp1aqLNoQKtM+yyZGRwllSxhm5P5+6NXMCOIAb3rN4JhoDSQoOFKkZvnNctxiPal5g7EyEYV1+0mShTsgnOTljwVLajdsQzkKIZLRlYkSIePuWcquPzcjvSIp/iBqW7Z2UXrQdbBfcggeMJZtQEVCmhHjJlXxmspYNpQP7czazjp6zQ5WwS/t8z0zW+3LqmP7M2RWKfRU0CPNuvIJK+ySnGJsl+vGG2uxliz7ZnIL7dHF+gO6c/iDVtZI+InZT5krl0XhKwOlAY88+1pPt8f/dAwF6St0utmK9r39w1+bmmrRu84CG8W5tnBXmqDxqUrz+UFUBg43zqCZ/mrjIedf/f6gCn97zR+xZYEWXiCX5vlknmlSerwlGo7KhrpuYM9ZLK7iqSGO8wN+Z1rMf80wg+kOBzo536WvgWEPKw3qCYvsDffGkNU4GjPfLB/m1DcuJf5eg/WhA6WEdauH52hh7Ks3lG15brUE0dei7x0HtcfDtd+MVaKjNLXx8B/o3f5+nl+g3vqUgG8ETnuCVTo/9YGHAqgRZK0SIaBNe7eBqPiXRpG+ySWkyg+NG4rMCBuin6yaXPYrKdHyjzRY5+csOcj1OgF96+qsaFN8i2YbjQUzZiaQPnV4GAsK80Bc8rkJMZXTAvYZnYyMaUBuH4+EJUKlIvj0G5iDdF5vDf5i0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
