travis:
  secure:
    BINSTAR_TOKEN: HzxNFiB3R5xfN8+zzWkpz6tcNJ7POOTWGvdcXDsEtxcVSsPplFeGbC8G7HTsLNTrbGcnTPtP65atUKdByNoaaWAsVORuGIDZycUVI1vTJb77j9a1Vo+CVm1YqIl6S2MbsPTImUgp6h/aKxP70WTAcG8gN96VBFe4Rlw4bdWflK9aq7+myOXTpJF1VEniB9hR56C4nMOdnYWRlUl7ynh/Xz94RvRO8trBAoSq3g28nLk5JBdrVzo8ubhIC3diTTfHJrz0UU05Y8unz+1aE5yOhqJFEUSgQGXFUduaoKRVhC7Zu6C5N2x0uv5LVRR2TQ5cZJcQEXQy3kC4V7aESGAc/VLmB/th3CvnsU9D6SuQpTqzAmElUcU1ZBf+JgkonnLLtm8OpJXiMHf5ww95vmECQNbDUKycib504TaUWJ4AgeeTwYsXRk+DBAuqm0y+gcRf+ptx05d7PAN4Bkh/Wy2n3lHlLLGCX+iqoe07zyB4QYRXCovGXi5iHRgOsCnbxifH4sbRF3OeQmz30Z3iJ7Z+NfMzkl1YV4PpPG0fSBJgjzycTo85X/zmnaMF/rvBZusfsNBqQaY9rXMwh1Tc4t2MkeNw/FLIX4AzhxYmeAcwpsPkiJZJQtzwMj/t+XjEkie1V+t7gw0WnrpGVBHt7qcrNT1pc3yWtBqNw3MY8CmsLh0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
